### ISSUE TITLE
[Bug] Server lists me as playing on server even though previous connection failed with Socket Closed Code 3

### ISSUE THREAD

**Issue by antoniogermano** [BeamMP/BeamMP#97] opened 2021-03-20 20:50 UTC
Hi :) love BeamMP, I'd like to help with whatever I can. I found this issue.

I'm using BeamMP 1.80.95.
When I tried to join a server, I got the Socket Closed Code 3 error. I already have BeamNG and BeamMP Launcher allowed on Windows Defender Firewall, so I tried again.

On the second try, I couldn't connect to the server. It told me "invalid key file, please restart the game".
So I did. Now when I try to connect to that server for the third time, BeamMP tells me I'm already playing on the server. See below:
![FullSizeRender 4](https://user-images.githubusercontent.com/816290/111885059-38789300-89a4-11eb-8474-1d92d849feb0.jpg)
And I also got Socket Closed Code 3 again (on the third try). Does anyone know how to fix this issue?

Thank you very much.

**Comment by Anonymous-275** [comment] 2021-03-20 21:03
Hello! If you are using a guest account that would be why, some servers do not allow you to join as a guest, and it will invalidate your key when you use it.

**Comment by antoniogermano** [comment] 2021-03-20 21:11
Thank you for the (very) fast response!

I'm actually logged in as user (not as guest), this is my account name. I was able to connect to another server earlier, but not this server. It has a lot of mods, does this has anything to do with it?

**Comment by Anonymous-275** [comment] 2021-03-20 21:15
Quite possibly, some mods make the launcher crash for whatever reason, the system will be revised and fixed. You could try connecting without any mods to make sure the server works in the first place.

**Comment by Anonymous-275** [comment] 2021-03-20 21:18
There is also currently a bug with the server keeping your "clone" alive instead of terminating that old connection, it could also have todo with this.

**Comment by Starystars67** [comment] 2021-03-23 16:48
A new update with work towards issues like this is in the works at the moment with a hopeful release date sometime next month for early access testing. Assuming all works out well & remains on track then we should see it in the public in around a month.

**Comment by lionkor** [comment] 2021-03-23 19:27
To clarify; the "clone" issue where you see yourself in a playerlist of a server is fixed in the coming release.

**Comment by Starystars67** [comment] 2021-04-06 11:31
@lionkor was this fixed by server version 2.0.3?

**Comment by lionkor** [comment] 2021-04-06 11:35
Oh damn, not sure why this issue was kept here. This specifically was fixed by v2.0.
v2.0.3 provides a workaround for this same issue occuring in a different situation.

I had assumed everyone had read the changelog for v2.0 and that any issues outside of BeamMP-Server were handled by others. That was my mistake. Consider this fixed.

**Comment by ZdrytchX** [comment] 2024-01-07 14:41
Had a recurrance of this bug:
![image](https://github.com/BeamMP/BeamMP/assets/1125998/cc7ad8d3-b4ef-4f75-8494-c1d24b37b7d4)
Last thing I remember was I was trying to unhitch a car (owned by my client) from a helicopter (Also owned by my client) and the game froze so I killed it with task manager.

**Comment by WiserTixx** [comment] 2024-09-15 18:38
@ZdrytchX This is not a bug, it's a result of the serverlist not updating instantly.

**Closed by WiserTixx** 2024-09-15 18:38 UTC
Labels: bug

**Comment by ZdrytchX** [comment] 2024-10-03 01:16
> @ZdrytchX This is not a bug, it's a result of the serverlist not updating instantly.

I haven't had the issue since since it is a rare occurance, but I suspect its because I had to kill the game directly which didn't send info to the server to remove me from the client list, so people were able to play on it fine but I couldn't reconnect (but could connect to other servers)

Other multiplayer games are affected by a similar issue too, but they generally solve it by adding a time-out function which kicks the "unresponsive" dead linked client from the server. In this case Dukedecahedron restarted the server after like half an hour to update something else which solved the issue iirc, could ask him for details if he still remembers.

Interestingly I had a similar client slot related issue on a mod I was making for tremulous a while back where a bot could invade the same slot that a player used, resulting in a zombie-like state where when the client loses connection, the bot takes over control of the avatar and plays like a normal bot, and whenever the player got within range of a target, the bot automatically attacked like a trigger bot, it was quite interesting.
